name: Build Windows

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/build-windows.yml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          echo "Building for Windows x86_64"
          cargo build --release --target x86_64-pc-windows-msvc
          echo "Build completed successfully"

      - name: Prepare binaries
        run: |
          mkdir release
          copy target\x86_64-pc-windows-msvc\release\rust-r2-cli.exe release\
          copy target\x86_64-pc-windows-msvc\release\rust-r2-gui.exe release\
          Compress-Archive -Path release\* -DestinationPath rust-r2-Windows-x86_64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-r2-Windows-x86_64
          path: rust-r2-Windows-x86_64.zip

