name: Build Linux (Fedora/RHEL)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/build-fedora.yml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-fedora:
    name: Build for Fedora/RHEL
    runs-on: ubuntu-latest
    container: fedora:latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          dnf update -y
          dnf install -y \
            gcc \
            gcc-c++ \
            make \
            openssl-devel \
            pkg-config \
            gtk3-devel \
            libxcb-devel \
            libxkbcommon-devel \
            fontconfig-devel \
            atk-devel \
            gdk-pixbuf2-devel \
            pango-devel \
            cairo-devel \
            curl \
            git \
            tar \
            gzip

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustc --version
          cargo --version

      - name: Get version and date
        id: metadata
        run: |
          source $HOME/.cargo/env
          VERSION=$(grep "^version" Cargo.toml | head -1 | cut -d'"' -f2)
          DATE=$(date +'%Y%m%d')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "Version: $VERSION, Date: $DATE"

      - name: Build
        run: |
          source $HOME/.cargo/env
          echo "Building for Fedora/RHEL x86_64"
          echo "Rust version: $(rustc --version)"
          cargo build --release --verbose
          echo "Build completed successfully"

      - name: Prepare release
        id: prepare
        run: |
          VERSION="${{ steps.metadata.outputs.version }}"
          DATE="${{ steps.metadata.outputs.date }}"
          ARCHIVE_NAME="rust-r2_v${VERSION}_${DATE}_Linux-Fedora-x64.tar.gz"
          
          mkdir -p release
          cp target/release/rust-r2-cli release/
          cp target/release/rust-r2-gui release/
          cp README.md LICENSE release/
          
          tar czf "${ARCHIVE_NAME}" -C release .
          
          echo "archive_name=${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
          echo "Created archive: ${ARCHIVE_NAME}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.metadata.outputs.version }}-${{ steps.metadata.outputs.date }}-Linux-Fedora
          name: Linux Fedora/RHEL - v${{ steps.metadata.outputs.version }} (Build ${{ steps.metadata.outputs.date }})
          body: |
            ## Linux Fedora/RHEL Build
            
            **Version:** ${{ steps.metadata.outputs.version }}
            **Build Date:** ${{ steps.metadata.outputs.date }}
            **Architecture:** x86_64
            **Compatible with:** Fedora 36+, RHEL 8+, CentOS 8+, Rocky Linux 8+
            
            ### Installation
            
            1. **Download and extract:**
            ```bash
            tar -xzf ${{ steps.prepare.outputs.archive_name }}
            ```
            
            2. **Make executable (Required on Linux):**
            ```bash
            chmod +x rust-r2-*
            ```
            
            3. **Run the application:**
            ```bash
            ./rust-r2-gui  # For GUI
            ./rust-r2-cli  # For CLI
            ```
            
            ### Dependencies
            If you encounter missing library errors, install:
            ```bash
            sudo dnf install gtk3 openssl
            ```
          files: ${{ steps.prepare.outputs.archive_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}