name: Test Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "GitHub Actions is working!"
          echo "Time: $(date)"
          echo "Runner: ${{ runner.os }}"